checks:
  php: true

filter:
  paths:
    - src/

build:
  image: default-bionic

  environment:
    php:
      version: 8.1.20
      ini:
        xdebug.mode: coverage
        idle_timeout: 600

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      dependencies:
        override:
          - pecl channel-update pecl.php.net
          - pecl install grpc-1.56.0
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
          - vendor/bin/rr get-binary
          - sudo cp ./rr /usr/local/bin/rr
          - rr -s -w=$(pwd) serve &

      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover ./coverage.xml
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
