checks:
  php: true

filter:
  paths:
    - src/

build:
  image: default-bionic

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      services:
        roadrunner:
          image: spiralscout/roadrunner:2023.1.5
          ports:
            - 9001
          commands:
            - command: rr -s -w=$(pwd) serve &
            - pwd
      environment:
        php:
          version: 8.1.20
          pecl_extensions:
            - grpc-1.56.0
          ini:
            xdebug.mode: coverage
      dependencies:
        override:
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover ./coverage.xml
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
