checks:
  php: true

filter:
  paths:
    - src/

build:
  image: default-bionic

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      environment:
        docker: true
      dependencies:
        override:
          - docker-compose up -d --build

      tests:
        override:
          - command: docker-compose run yii-runner-roadrunner vendor/bin/phpunit --coverage-clover ./coverage.xml
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
