checks:
  php: true

filter:
  paths:
    - src/

build:
  image: default-bionic

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      environment:
        php:
          version: 8.1.20
          pecl_extensions:
            - grpc-1.56.0
          ini:
            xdebug.mode: coverage

      dependencies:
        override:
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
          - vendor/bin/rr get-binary
          - cp ./rr /usr/local/bin/rr
          - rr -s -w=$(pwd) serve &

      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover ./coverage.xml
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
