on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches: ['master']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php: ['8.1', '8.2', '8.3', '8.4', '8.5']

    steps:
      - name: Checkout.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: memory_limit=-1
          coverage: pcov
          tools: composer:v2
          extensions: grpc-1.56.0 sockets

      - name: Install dependencies with composer.
        run: composer update --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Get RoadRunner binary
        run: |
          vendor/bin/rr get-binary
          cp ./rr /usr/local/bin/rr

      - name: Start RoadRunner
        run: rr -s -w=$(pwd) serve &

      - name: Run tests with code coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always --configuration phpunit.xml.dist

      - name: Upload coverage to Codecov.
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
