on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

name: mutation test

permissions:
  contents: read
jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php: ['8.5']

    steps:
      - name: Checkout.
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45
        with:
          php-version: ${{ matrix.php }}
          ini-values: memory_limit=-1
          coverage: pcov
          tools: composer:v2
          extensions: grpc-1.56.0 sockets

      - name: Install dependencies with composer.
        run: composer update --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Get RoadRunner binary
        run: |
          vendor/bin/rr get-binary
          cp ./rr /usr/local/bin/rr

      - name: Start RoadRunner
        run: rr -s -w=$(pwd) serve &

      - name: Run infection
        run: vendor/bin/roave-infection-static-analysis-plugin --threads=2 --ignore-msi-with-no-mutations
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
